      SUBROUTINE GLOOP
C
      save
      include "ptrunk"
      include "pimax"
      include "pjmax"
      include "pkmax"
      include "comcom"
C-----------------------------------------------------------------------
      COMMON/SCRTCH/QWORK(MNWV3,3),GWORK(IMX,KGMAX)
      include "comnum"
      include "commnt"
      include "comtim"
      include "comphc"
      COMMON/BSCST/    QZEBAR(MNWV2,KMAX), QDIBAR(MNWV2,KMAX),
     1   QTMBAR(MNWV2,KMAX),  QPSBAR(MNWV2),  QUBAR(MNWV3,KMAX),
     2   QVBAR(MNWV3,KMAX),QPHBAR(MNWV3),QPLBAR(MNWV2)              
C
      COMMON/GRBSC/
     2 GBDIVN(IMX,KMAX),GBTMPN(IMX,KMAX),GBROTN(IMX,KMAX),
     3 GBUN  (IMX,KMAX),GBVN  (IMX,KMAX),
     4 GBPLMN(IMX),GBPPHN(IMX),GBLNPN(IMX),
C
     2 GBDIVS(IMX,KMAX),GBTMPS(IMX,KMAX),GBROTS(IMX,KMAX),
     3 GBUS  (IMX,KMAX),GBVS  (IMX,KMAX),
     4 GBPLMS(IMX),GBPPHS(IMX),GBLNPS(IMX)
      COMMON/TSFCA/ TSA(MNWV2)
      COMMON/GTSFCA/ GTSAN(IMX),GTSAS(IMX)
      DIMENSION BRLVOR(KMAX),BABSVR(KMAX)
C
      DATA IFP/1/
      IF(IFP.EQ.1) THEN
      MEND2 =MEND1*2
      JEND2 =JEND1+1
C
      CORIOL=SQRT(TWO/THREE)*TWOMG
      ROOT2 =SQRT(TWO)
      END IF
C
      CALL DELLNP(QLNPP,QPPHI,QPLAM,EPS,MEND1,NEND1,NEND2,JEND1,
     1            MNWV0,MNWV1,LA0,LA1)
      CALL DZTOUV(QDIVP,QROTP,QUP,QVP,EPS,MEND1,NEND1,NEND2,JEND2,MNWV0,
     1            MNWV1,KMAX,LA0,LA1,QWORK(1,1),QWORK(1,2))
C
C     RELATIVE TO ABSOLUTE VORTICITY
CVD$L NOVECTOR
      DO 100 K=1, KMAX
      RELVOR(K) = QROTP(MEND2+1,K)
      BRLVOR(K) = QZEBAR(MEND2+1,K)
C   RELATIVE VORTICITY ONLY FOR ANOMALIES
      ABSVOR(K) = RELVOR(K)
      BABSVR(K) = BRLVOR(K)+CORIOL
      QROTP(MEND2+1,K)  = ABSVOR(K)
      QZEBAR(MEND2+1,K) =BABSVR(K)
100   CONTINUE
CVD$R NOLSTVAL
C     DO 140 K=1,KMAX
C     DO 140 MN=1,MNWV2
C     QDIVT(MN,K)=QGZS(MN)
C140   CONTINUE
C*** QDIVT NOW CONTAINS CONTRIB. FROM TOPOG.***
      CALL RESET(QTMPT,MNWV2* KMAX)
      CALL RESET(QROTT,MNWV2* KMAX)
      CALL RESET(QDIVT,MNWV2* KMAX)
      CALL RESET(QDOTT,MNWV2* KMAX)
C
C=======================================================================
C=========  LAT LOOP ===================================================
C=======================================================================
C
      DO 1000 LAT = 1, JMAXHF
      LOT=6*KMAX+3
      LOTB = (5*KMAX+3)*2
      CALL RESET(GDIVN,IMX*LOT)
      CALL RESET(GDIVS,IMX*LOT)
      CALL RESET(GBDIVN,IMX*LOTB)
C
      CALL PLN2(PLN,DCOLRA,LAT,DEPS,MEND1,NEND2,JEND2,MNWV1,JMAXHF,LA1)
C
      DO 300 MN=1,MNWV1
      QLN(2*MN-1)=PLN(MN)
      QLN(2*MN  )=PLN(MN)
  300 CONTINUE
C ...     FOR ZONAL MEANS
      CALL SUMPLV(QPHBAR,GBPPHN,GBPPHS,QLN,
     1            IMX,MEND1,NEND2,JEND2,MNWV3,    1,QWORK)
      CALL SUMPLV(QUBAR  ,GBUN   ,GBUS   ,QLN,
     1            IMX,MEND1,NEND2,JEND2,MNWV3, KMAX,QWORK)
      CALL SUMPLV(QVBAR  ,GBVN   ,GBVS   ,QLN,
     1            IMX,MEND1,NEND2,JEND2,MNWV3, KMAX,QWORK)
C ,,,     AND FOR ANAOMALIES
      CALL SUMPLV(QPPHI,GPPHIN,GPPHIS,QLN,
     1            IMX,MEND1,NEND2,JEND2,MNWV3,    1,QWORK)
      CALL SUMPLV(QUP  ,GUN   ,GUS   ,QLN,
     1            IMX,MEND1,NEND2,JEND2,MNWV3, KMAX,QWORK)
      CALL SUMPLV(QVP  ,GVN   ,GVS   ,QLN,
     1            IMX,MEND1,NEND2,JEND2,MNWV3, KMAX,QWORK)
      IF(JEND1.NE.NEND1+MEND1-1) THEN
      L=0
      DO 320 NN=1,NEND1
      IF(NN.LE.JEND1-MEND1+1) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND1-NN+1
      END IF
      DO 320 MM=1,MMAX
      L=L+1
      LX=LA1(MM,NN)
      QLN(2*L-1)=PLN(LX)
      QLN(2*L  )=PLN(LX)
  320 CONTINUE
      END IF
C ...  FOR ZONAL MEANS
      CALL SUMPLS(QPSBAR,GBLNPN ,GBLNPS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2,    1,QWORK)
      CALL SUMPLS(QPLBAR,GBPLMN,GBPLMS,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2,    1,QWORK)
      CALL SUMPLS(QDIBAR,GBDIVN ,GBDIVS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
      CALL SUMPLS(QTMBAR,GBTMPN ,GBTMPS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
      CALL SUMPLS(QZEBAR,GBROTN ,GBROTS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
C
      CALL SUMPLS(QLNPP,GLNPN ,GLNPS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2,    1,QWORK)
      CALL SUMPLS(TSA,GTSAN ,GTSAS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2,    1,QWORK)
      CALL SUMPLS(QPLAM,GPLAMN,GPLAMS,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2,    1,QWORK)
      CALL SUMPLS(QDIVP,GDIVN ,GDIVS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
      CALL SUMPLS(QTMPP,GTMPN ,GTMPS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
      CALL SUMPLS(QROTP,GROTN ,GROTS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
      CALL SUMPLS(QDOTP,GDOTN ,GDOTS ,QLN,
     1            IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
C
      LATCO=LAT
      RCL=RCS2(LAT)
C.....
      CALL GFIDI(GKEN,
     |          GDIVN,GTMPN,GROTN,GUN,GVN,GDOTN,GPLAMN,GPPHIN,GLNPN,
     1          GBDIVN,GBTMPN,GBROTN,GBUN,GBVN,GBPLMN,GBPPHN,GBLNPN,
     2          GTSAN,COLRAD,RCL,IMX)
C
      LATCO= JMAX +1-LAT
      CALL GFIDI(GKES,
     |          GDIVS,GTMPS,GROTS,GUS,GVS,GDOTS,GPLAMS,GPPHIS,GLNPS,
     1          GBDIVS,GBTMPS,GBROTS,GBUS,GBVS,GBPLMS,GBPPHS,GBLNPS,
     2          GTSAS,COLRAD,RCL,IMX)
C.....
      KKMAX=7*KMAX
      CALL SYMASY(GKEN ,GKES ,GWORK,IMX,KKMAX)
C...
      DO 400 MN=1,MNWV1
      QLN(2*MN-1)=PLN(MN)*WGT(LAT)
      QLN(2*MN  )=PLN(MN)*WGT(LAT)
400   CONTINUE
C
      CALL FL22(GTMPN ,GTMPS ,QTMPT,QLN,
     1          IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
      CALL FL22(GDOTN ,GDOTS ,QDOTT,QLN,
     1          IMX,MEND1,NEND1,JEND1,MNWV2, KMAX,QWORK)
C.....
      CALL GOZRIM(PLN,DER,DEPS,LAT,PLNWCS,RCS2,WGT(LAT),MEND1,
     1            NEND1,NEND2,JEND1,MNWV0,MNWV1,JMAXHF,QWORK,LA1)
      IF(JEND1.EQ.MEND1+NEND1-1) THEN
      DO 480 MN=1,MNWV0
      QLN(2*MN-1)=PLN(MN)
      QLN(2*MN  )=PLN(MN)
  480 CONTINUE
      ELSE
      L=0
      DO 500 NN=1,NEND1
      IF(NN.LE.JEND1-MEND1+1) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND1-NN+1
      END IF
      DO 500 MM=1,MMAX
      L=L+1
      LX=LA1(MM,NN)
      QLN(2*L-1)=PLN(LX)
      QLN(2*L  )=PLN(LX)
  500 CONTINUE
      END IF
      DO 520 MN=1,MNWV0
      QDER  (2*MN-1)=DER   (MN)
      QDER  (2*MN  )=DER   (MN)
      QLNWCS(2*MN-1)=PLNWCS(MN)
      QLNWCS(2*MN  )=PLNWCS(MN)
520   CONTINUE
C..
      CALL PSU22(GROTS,GROTN,GDIVS,GDIVN,QDIVT,QLNWCS,QDER,
     1           IMX,MEND1,NEND1,JEND1,MNWV2,KMAX ,QWORK)
      CALL MSU22(GROTS,GROTN,GDIVS,GDIVN,QROTT,QLNWCS,QDER,
     1           IMX,MEND1,NEND1,JEND1,MNWV2,KMAX ,QWORK)
      CALL MSU22(GUS  ,GUN  ,GVS  ,GVN  ,QTMPT,QLNWCS,QDER,
     1           IMX,MEND1,NEND1,JEND1,MNWV2,KMAX ,QWORK)
C...  FL22 ACTS HERE AS LAPLACIAN  . SEE OUTPUT FROM GOZRIM
      CALL FL22 (GKEN ,GKES ,QDIVT,QLN  ,
     1           IMX,MEND1,NEND1,JEND1,MNWV2,KMAX ,QWORK)
C...
1000   CONTINUE
C
C  RESTORE BASIC STATE RELATIVE VORTICITY
      DO 600 K=1,KMAX
      QZEBAR(MEND2+1,K) =BRLVOR(K)
 600  CONTINUE
C
      RETURN
      END
