CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  from U & V wind component compute
C       vorticity
C  The required subroutines are in rvdvvpst.f
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE DIV2DSP(UWND,VWND,DIVGD)
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1,NM=NW,NMP=NM+1)
      PARAMETER(NLATG=102,NLONG=128)
      DIMENSION UWND(NLONG,NLATG),VWND(NLONG,NLATG)
      DIMENSION DIVS(2,NLEG,NMP),VORS(2,NLEG,NMP)
      DIMENSION DIVGD(NLONG,NLATG)
CCC---CALCULATE SPECTRAL DIVERGENCE AND VORTICITY
      CALL GCMCRC(UWND,VWND,DIVS,VORS)
C-----transform divergence to GRID
      CALL EVLSCA(VLPS,VELPOT)
      RETURN
      END
 
