CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     compute Q.G. potential vorticity               
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE QGPTV
      PARAMETER(NW=40,NLEG=NW+1,NMP=NW+1)
      PARAMETER(NLATG=102,NLONG=128,NMAND=7,MAND=NMAND-2)
      COMMON/EPSLON/EPS(NLEG,NMP),XXN(NLEG,NMP),XXM(NMP)
      COMMON/CORCOS/CORIOLIS(NLATG),PLEVEL(NMAND)  
      COMMON/PTV/EDYPTV(NLONG,NLATG,MAND),EDYGDT(NLONG,NLATG,NMAND),
     1           EDSPRV(2,NMP,NLEG,MAND)),EDYGRV(NLONG,NLATG,MAND),
     2           EDYSPS(2,NMP,NLEG,MAND),GLBAVT(NMAND)
      GASCON=287.
      XKAPA=287./1004.       
      R=6.371E+06
      RR=R*R
      DO 715 L=1,MAND
      DO 715 K=1,NMP
      DO 715 J=1,NLEG 
      DO 715 I=1,2 
      EDSPRV(I,J,K,L)=-(XXN(J,K)+1)*XXN(J,K)*EDYSPS(I,J,K,L+1)
     1/RR
  715 CONTINUE
      DO 720 L=1,NMAND
         CALL EVLSCA(EDSPRV(1,1,1,L),EDYGRV(1,1,L))
  720 CONTINUE
      DO 725 K=1,MAND
      DO 725 J=1,NLATG
      DO 725 I=1,NLONG
      FT1=CORIOLIS(J)/
     1    (PLEVEL(K)-PLEVEL(K+2)) 
      FT2=(EDYGDT(I,J,K+1)+EDYGDT(I,J,K+2))*
     1    (PLEVEL(K+1)-PLEVEL(K+2))/                  
     2    (GLBAVT(K+2)-GLBAVT(K+1))
      FT3=(EDYGDT(I,J,K)+EDYGDT(I,J,K+1))*
     1    (PLEVEL(K)-PLEVEL(K+1))/                  
     2    (GLBAVT(K+1)-GLBAVT(K))
      TERM3=FT1*(FT2-FT3)
      EDYPTV(I,J,K)=EDYGRV(I,J,K)+TERM3
  725 CONTINUE
      RETURN
      END

