      PARAMETER(NLONG=128)
      PARAMETER(NLATG=102)
      PARAMETER(NMAND=7,MAND=NMAND-2)
      DIMENSION AVGGDT(NLONG,NLATG,NMAND),AVGGDH(NLONG,NLATG,NMAND)
      DIMENSION AVGGDU(NLONG,NLATG,NMAND),AVGGDV(NLONG,NLATG,NMAND)
      DIMENSION GGRPVX(NLONG,NLATG,MAND),GGRPVY(NLONG,NLATG,MAND)
      DIMENSION AVEDUU(NLONG,NLATG,MAND),AVEDVV(NLONG,NLATG,MAND)
      DIMENSION AVEDUV(NLONG,NLATG,MAND),AVEDUT(NLONG,NLATG,MAND)
      DIMENSION AVEDVT(NLONG,NLATG,MAND),AVEDTT(NLONG,NLATG,MAND)
      DIMENSION AVEDES(NLONG,NLATG,MAND)                          
      DIMENSION GRDESX(NLONG,NLATG,MAND),GRDESY(NLONG,NLATG,MAND) 
      DIMENSION AVEDUQ(NLONG,NLATG,MAND),AVEDVQ(NLONG,NLATG,MAND)
      OPEN(10,FILE='~/ppt/gcm1/gtwv87w.hp',FORM='UNFORMATTED',
     +RECORDTYPE='STREAM',CONVERT='BIG_ENDIAN')
      OPEN(60,FILE='avggdh.dat',FORM='FORMATTED')
      OPEN(61,FILE='avggdt.dat',FORM='FORMATTED')
C
CC====read the data from cray                           
C
      IUNIT=10
      READ(IUNIT) AVGGDH
      READ(IUNIT) AVGGDU
      READ(IUNIT) AVGGDV
      READ(IUNIT) AVGGDT
      READ(IUNIT) AVEDUU
      READ(IUNIT) AVEDVV
      READ(IUNIT) AVEDUV
      READ(IUNIT) AVEDUT
      READ(IUNIT) AVEDVT
      READ(IUNIT) AVEDTT
      READ(IUNIT) AVEDES
      READ(IUNIT) AVEDUQ
      READ(IUNIT) AVEDVQ
      READ(IUNIT) EDYGDS
  999 FORMAT(6E12.4)
      JUNIT=60      
      WRITE(JUNIT,999) AVGGDH
      JUNIT=JUNIT+1
      WRITE(JUNIT,999) AVGGDT
      STOP
      END
 

