
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C     compute  potential vorticity with relative vort from U & V
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE UVPTV(UWN,VWN)
      PARAMETER(NW=40,NLEG=NW+1,NMP=NW+1)
      PARAMETER(NLATG=102,NLONG=128,NMAND=7,MAND=NMAND-2)
      COMMON/EPSLON/EPS(NLEG,NMP),XXN(NLEG,NMP),XXM(NMP)
      COMMON/CORCOS/CORIOLIS(NLATG),PLEVEL(NMAND)  
      DIMENSION UWN(NLONG,NLATG,NMAND),VWN(NLONG,NLATG,NMAND)             
      COMMON/PTV/AVSPRV(2,NLEG,NMP,NMAND),AVGDRV(NLONG,NLATG,NMAND),
     1           AVGPTV(NLONG,NLATG,MAND),PTVT3(NLONG,NLATG,MAND),
     2           AVGPTT(NLONG,NLATG,NMAND),AVDPTT(NLONG,NLATG,NMAND),
     3           GLBAVT(NMAND)
      GASCON=287.
      XKAPA=287./1004.       
      R=6.371E+06
      RR=R*R
C.....have relative vort
      DO 100 L=1,NMAND
C     CALL RELVOT(UWN(1,1,L),VWN(1,1,L),AVSPRV(1,1,1,L))
      CALL RLVORT(UWN(1,1,L),VWN(1,1,L),AVGDRV(1,1,L))
  100 CONTINUE
C     DO 720 L=1,NMAND
C        CALL EVLSCA(AVSPRV(1,1,1,L),AVGDRV(1,1,L))
C 720 CONTINUE
      DO 725 K=1,MAND
      DO 725 J=1,NLATG
      DO 725 I=1,NLONG
      FT1=CORIOLIS(J)/(PLEVEL(K)-PLEVEL(K+2))
      FT2=(AVDPTT(I,J,K+2)+AVDPTT(I,J,K+1))* 
     1    (PLEVEL(K+1)-PLEVEL(K+2))/
     2    (GLBAVT(K+2)-GLBAVT(K+1))
      FT3=(AVDPTT(I,J,K+1)+AVDPTT(I,J,K))* 
     1    (PLEVEL(K)-PLEVEL(K+1))/
     2    (GLBAVT(K+1)-GLBAVT(K))
      TERM3=FT1*(FT2-FT3)
      PTVT3(I,J,K)=TERM3
      AVGPTV(I,J,K)=CORIOLIS(J)+AVGDRV(I,J,K+1)+TERM3
  725 CONTINUE
      RETURN
      END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C     compute spectral relative vort by using wind U & V
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE RELVOT(UWNREA,VWNREA,VORSPX)
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1,NM=NW,NMP=NM+1,NLEGP=NLEG+1)
      PARAMETER(NLATG=102 ,KHALF=(NLATG+1)/2,NLONG=128 ,NLONGP=NLONG+1)
      PARAMETER(IMAXT=3*NLONG/2)
      PARAMETER(EA=6.371E+06)
      COMMON/GAUSS/RADG(NLATG),GWGT(NLATG)
      COMMON/POLY1/PLEG(NLEGP,NMP,NLATG),DPLEG(NLEGP,NMP,NLATG)
      COMMON/FFTAR1/TRIGS(IMAXT),IFAX(10)
      COMMON/FFTAR2/ARRAY(NLONGP,NLATG),WORK(NLONGP,NLATG)
      COMMON/FLDWAV/UWNWAV(2,NMP,NLATG),VWNWAV(2,NMP,NLATG)     
      DIMENSION VORSPX(2,NLEG,NMP),VORGRD(NLONG,NLATG)         
      DIMENSION UWNREA(NLONG,NLATG),VWNREA(NLONG,NLATG)             
      PI=ACOS(-1.)
C....WINDS MUST BE MULTIPLIED BY COS(LAT)
      DO 100 J=1,NLATG
      DO 100 I=1,NLONG
         UWNREA(I,J)=UWNREA(I,J)*COS(RADG(J))
         VWNREA(I,J)=VWNREA(I,J)*COS(RADG(J))
  100 CONTINUE
      CALL FTRANS(UWNREA,UWNWAV)
      CALL FTRANS(VWNREA,VWNWAV)
CCC---CALCULATE SPECTRAL VORTICITY FROM MODIFIED WINDS
      CALL VORWAV(UWNWAV,VWNWAV,VORSPX)
      RETURN
      END
 
      SUBROUTINE FTRANS(GRID,WAVE)
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1,NM=NW,NMP=NM+1)
      PARAMETER(NLATG=102 ,NLONG=128 ,NLONGP=NLONG+1,IMAXT=3*NLONG/2)
      COMMON/FFTAR1/TRIGS(IMAXT),IFAX(10)
      COMMON/FFTAR2/ARRAY(NLONGP,NLATG),WORK(NLONGP,NLATG)
      DIMENSION GRID(NLONG,NLATG),WAVE(2,NMP,NLATG)
      DO 60 JG=1,NLATG
      DO 40 IG=1,NLONG
      ARRAY(IG,JG)=GRID(IG,JG)
   40 CONTINUE
      ARRAY(NLONGP,JG)=0.0
   60 CONTINUE
      ISIGN=-1
      INC=1
      JUMP=NLONGP
      LOT=NLATG
      CALL FFT991(ARRAY,WORK,TRIGS,IFAX,INC,JUMP,NLONG,LOT,ISIGN)
      DO 200 JG=1,NLATG
      DO 200 IM=1,NMP
      WAVE(1,IM,JG)=ARRAY(2*IM-1,JG)
      WAVE(2,IM,JG)=ARRAY(2*IM  ,JG)
  200 CONTINUE
      RETURN
      END
 
      SUBROUTINE VORWAV(U,V,VORT)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C   PROGRAM TO TAKE THE WAVE REPRESENTATIONS OF THE MODIFIED     C  
C   WINDS AND CALCULATE THE SPECTRAL VORTICITY.                  C
C   IT IS ASSUMED THAT THE WINDS HAVE ALREADY BEEN MULTIPLIED    C
C   BY COS(LATITUDE)                                             C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1,NM=NW,NMP=NM+1,NLEGP=NLEG+1)
      PARAMETER(NLATG=102 ,NLONG=128 ,NLONGP=NLONG+1,IMAXT=3*NLONG/2)
      PARAMETER(EA=6.371E+06)
      COMMON/POLY1/PLEG(NLEGP,NMP,NLATG),DPLEG(NLEGP,NMP,NLATG)
      COMMON/GAUSS/RADG(NLATG),GWGT(NLATG)
      DIMENSION U(2,NMP,NLATG),V(2,NMP,NLATG)
      DIMENSION VORT(2,NLEG,NMP) 
      CALL FILLAR(VORT,0.0,2*NLEG*NMP)
      DO 300 J=1,NLATG
      COSR=COS(RADG(J))
      DO 200 IM=1,NMP
      XM=(IM-1)
      UREAL=U(1,IM,J)
      UIMAG=U(2,IM,J)
      VREAL=V(1,IM,J)
      VIMAG=V(2,IM,J)
      DO 180 N=1,NLEG
      VRE=(-XM*VIMAG*PLEG(N,IM,J)+UREAL*DPLEG(N,IM,J))
     1 /(COSR*COSR)
      VIM=(+XM*VREAL*PLEG(N,IM,J)+UIMAG*DPLEG(N,IM,J))
     1 /(COSR*COSR)
      VORT(1,N,IM)=VORT(1,N,IM)+GWGT(J)*VRE
      VORT(2,N,IM)=VORT(2,N,IM)+GWGT(J)*VIM
  180 CONTINUE
  200 CONTINUE
  300 CONTINUE
      DO 310 IM=1,NMP
      DO 310 N=1,NLEG
      DO 310 IC=1,2
      VORT(IC,N,IM)=VORT(IC,N,IM)/EA
  310 CONTINUE
      RETURN
      END

      SUBROUTINE FILLAR(ARRAYS,VALUE,N)
      DIMENSION ARRAYS(N)
      DO 20 I=1,N
      ARRAYS(I)=VALUE
   20 CONTINUE
      RETURN
      END

