
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  compute velocity UCOS(LAT) & VCOS(LAT) in spectral space
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE VELOSP(FIN,UU,VV)
      PARAMETER(NW=15,NLEG=NW+1,NMP=NW+1)
      COMMON/EPSLON/EPS(NLEG,NMP),XXN(NLEG,NMP),XXM(NMP)
      DIMENSION FIN(2,NLEG,NMP)                   
      DIMENSION UU(2,NLEG,NMP),VV(2,NLEG,NMP)
      R=6.371E+06
CC....compute  spectral U  
      DO 100 I=1,2
      DO 100 K=1,NMP
         DO 200 J=2,NW  
      UU(I,J,K)=((XXN(J,K)-1)*EPS(J,K)*FIN(I,J-1,K)-
     1(XXN(J,K)+2)*EPS(J+1,K)*FIN(I,J+1,K))/R
  200 CONTINUE
         UU(I,1,K)=-(XXN(1,K)+2)*EPS(2,K)*FIN(I,2,K)/R
         UU(I,NLEG,K)=(XXN(NLEG,K)-1)*EPS(NLEG,K)*
     1FIN(I,NW,K)/R
  100 CONTINUE
CC....compute  spectral V  
      DO 300 K=1,NMP
      DO 300 J=1,NLEG 
         VV(1,J,K)=-XXM(K)*FIN(2,J,K)/R
         VV(2,J,K)=XXM(K)*FIN(1,J,K)/R
  300 CONTINUE
      RETURN
      END

