CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C    compute the non div barotropic st wave activity flux using          C
C    2 year pressure history data(U,V only)                        C
C                                                                      C
C    1000,850,700,500,300,200,100                                      C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C   Needed Subroutings Are in Source Files:
C           fftgcm.f  genpnme.f   glats.f
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1)
      PARAMETER(NM=NW)
      PARAMETER(NMP=NW+1)
      PARAMETER(NLONG=128)
      PARAMETER(NLATG=102)
      PARAMETER(NMAND=7,MAND=2)
      PARAMETER(NLEGP=NLEG+1)
      PARAMETER(NLONGP=NLONG+1,IMAXT=3*NLONG/2)
      PARAMETER(KHALF=(NLATG+1)/2)
      COMMON/GAUSS/RADG(NLATG),GWGT(NLATG)
      COMMON/POLY1/PLEG(NLEG,NMP,NLATG),DPLEG(NLEG,NMP,NLATG)
      COMMON/FFTAR1/TRIGS(IMAXT),IFAX(10)
      COMMON/FFTAR2/ARRAY(NLONGP,NLATG),WORK(NLONGP,NLATG)
      COMMON/EPSLON/EPS(NLEG,NMP),XXN(NLEG,NMP),XXM(NMP)
      COMMON/CORCOS/CORIOLIS(NLATG),PLEVEL(NMAND)  
      REAL*8    COLRAD(KHALF),WGT(KHALF),WGTCS(KHALF),RCS2(KHALF)
      COMMON/STWV/AVGGDU(NLONG,NLATG,MAND),AVGGDV(NLONG,NLATG,MAND),
     1            AVGGDS(NLONG,NLATG,MAND),
     2            XFS(NLONG,NLATG,MAND),YFS(NLONG,NLATG,MAND),
     4            EDGDH(NLONG,NLATG,MAND),EDGDU(NLONG,NLATG,MAND),
     5            EDGDV(NLONG,NLATG,MAND),
     6            ZMH(NLATG,MAND),
     7            ZMU(NLATG,MAND),ZMV(NLATG,MAND)
      DIMENSION TOTU(NLONG,NLATG,MAND),TOTV(NLONG,NLATG,MAND)
      DIMENSION AVGPTV(NLONG,NLATG,MAND),AVGDRV(NLONG,NLATG,MAND)
      DIMENSION COSLAT(NLATG), POOVRP(NMAND)
      OPEN(10,FILE='/data/pool/peng/ec80_89/ec80_89djfuv',
     +FORM='UNFORMATTED')
      OPEN(11,FILE='/data/pool/peng/ec80_89/ec8283djfuv',
     +FORM='UNFORMATTED')
      OPEN(60,FILE='/data/pool/peng/stwv/ecndstwv',FORM='UNFORMATTED')
      OPEN(62,FILE='/data/pool/peng/ecndst',FORM='FORMATTED')
      DATA PLEVEL/100000.,85000.,70000.,50000.,30000.,20000.,10000./
      PI=ACOS(-1.0)
      LENS1=2*NLEG*NMP
      LENS2=2*NLEG*NMP*MAND
      LENG1=NLONG*NLATG
      LENG2=NLONG*NLATG*MAND
      LENGZ=MAND*NLATG
      R=6.371E+06
      RR=R**2
      UNDEF=-9.99E+33
      CALL GLATS(KHALF,COLRAD,WGT,WGTCS,RCS2)
      DO 30 K=1,KHALF
      RADG(K)=PI/2.0 - REAL(COLRAD(K))
      RADG(NLATG-K+1)=-RADG(K)
      GWGT(K)=REAL(WGT(K))
      GWGT(NLATG-K+1)=+GWGT(K)
   30 CONTINUE
      DO 40 JG=1,NLATG
      CALL GENPNME(RADG(JG),PLEG(1,1,JG),DPLEG(1,1,JG))
   40 CONTINUE
C.....Compute the CORIOLIS and COSLAT
      OMEGA=2*PI/(24.*3600.)
      DO 35 K=1,NLATG
         CORIOLIS(K)=2*OMEGA*SIN(RADG(K))
         COSLAT(K)=COS(RADG(K))
      WRITE(6,*) 'COSLAT=',K,COSLAT(K) 
   35 CONTINUE
      PRINT 103
  103 FORMAT(' befor reading data   ')
C
CC====read the data from cray                           
C
      IREAD=0
      IUNIT=10
  666 CONTINUE
      IREAD=IREAD+1
      PRINT 101,IREAD
  101 FORMAT('IREAD= ', I3)
      READ(IUNIT) TOTU 
      READ(IUNIT) TOTV
      WRITE(6,*) 'have got data'
C
C=====compute strm func and rot velocity 
C
      DO 50 L=1,2
      CALL RVDVVPST(TOTU(1,1,L),TOTV(1,1,L),AVGGDU(1,1,L),
     +     AVGGDV(1,1,L),AVGGDS(1,1,L),AVGDRV(1,1,L))
   50 CONTINUE
      CALL STWVFLX
      DO 55 K=1,2
      DO 55 J=1,NLATG
      DO 55 I=1,NLONG
         AVGPTV(I,J,K)=CORIOLIS(J)+AVGDRV(I,J,K)
   55 CONTINUE
C
CC====write out more selected quantities
C
      JUNIT=60
C.....avg strm funct
      CALL XWRITE(AVGGDS,JUNIT,LENG2)
C.....avg U & V
      CALL XWRITE(AVGGDU,JUNIT,LENG2)
      CALL XWRITE(AVGGDV,JUNIT,LENG2)
C.....avg relative vorticity 
      CALL XWRITE(AVGDRV,JUNIT,LENG2)
C.....eddies
      CALL XWRITE(EDGDH,JUNIT,LENG2)
      CALL XWRITE(EDGDU,JUNIT,LENG2)
      CALL XWRITE(EDGDV,JUNIT,LENG2)
C.....average PTV
      CALL XWRITE(AVGPTV,JUNIT,LENG2)
C.....stwvlfx
      CALL XWRITE(XFS,JUNIT,LENG2)
      CALL XWRITE(YFS,JUNIT,LENG2)
C.....zonal means      
      CALL XWRITE(ZMH,JUNIT,LENGZ)
      CALL XWRITE(ZMU,JUNIT,LENGZ)
      CALL XWRITE(ZMV,JUNIT,LENGZ)
      IF(IREAD.LT.2) THEN
        IUNIT=11
        GO TO 666
      END IF
999   format(6e13.4)
      write(62,999) AVGGDU
      STOP
      END
 
      SUBROUTINE XWRITE(ARRAY,JUNIT,N)
      DIMENSION ARRAY(N)
      WRITE(JUNIT) ARRAY
      RETURN
      END

      SUBROUTINE TRNSFM(FIELDG,FLDSPC)
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1)
      PARAMETER(NM=NW)
      PARAMETER(NMP=NW+1)
      PARAMETER(NLONG=128)
      PARAMETER(NLATG=102)
      PARAMETER(NLONGP=NLONG+1,IMAXT=3*NLONG/2)
      PARAMETER(KHALF=(NLATG+1)/2)
      COMMON/GAUSS/RADG(NLATG),GWGT(NLATG)
      COMMON/POLY1/PLEG(NLEG,NMP,NLATG),DPLEG(NLEG,NMP,NLATG)
      COMMON/FFTAR1/TRIGS(IMAXT),IFAX(10)
      COMMON/FFTAR2/ARRAY(NLONGP,NLATG),WORK(NLONGP,NLATG)
      DIMENSION FIELDG(NLONG,NLATG)
      DIMENSION FLDSPC(2,NLEG,NMP)
      DO 20 IM=1,NMP
      DO 20 IN=1,NLEG
      DO 20 IC=1,2
      FLDSPC(IC,IN,IM)=0.0
   20 CONTINUE
      DO 60 JG=1,NLATG
      DO 40 IG=1,NLONG
      ARRAY(IG,JG)=FIELDG(IG,JG)
   40 CONTINUE
      ARRAY(NLONGP,JG)=0.0
   60 CONTINUE
      ISIGN=-1
      INC=1
      JUMP=NLONGP
      LOT=NLATG
      CALL FFT991(ARRAY,WORK,TRIGS,IFAX,INC,JUMP,NLONG,LOT,ISIGN)
      DO 200 JG=1,NLATG
      DO 180 IM=1,NMP
      DO 180 IN=1,NLEG
      FLDSPC(1,IN,IM)=FLDSPC(1,IN,IM)+ARRAY(2*IM-1,JG)*PLEG(IN,IM,JG)*
     1 GWGT(JG)
      FLDSPC(2,IN,IM)=FLDSPC(2,IN,IM)+ARRAY(2*IM  ,JG)*PLEG(IN,IM,JG)*
     1 GWGT(JG)
  180 CONTINUE
  200 CONTINUE
      RETURN
      END


 
      SUBROUTINE XUPDTG(FIELD,AVE,NLON,NLAT)
      DIMENSION FIELD(NLON,NLAT),AVE(NLON,NLAT)
      DO 100 J=1,NLAT
      DO 100 I=1,NLON
      AVE(I,J)=AVE(I,J)+FIELD(I,J)
  100 CONTINUE
      RETURN
      END
 
      SUBROUTINE FORWRT(FLDSPC,N,JUNIT)
      DIMENSION FLDSPC(N)
      WRITE(JUNIT,7000) FLDSPC
 7000 FORMAT(5(E16.8))
      RETURN
      END
 
 

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  transform from spctral to Gaussian grid                        C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE EVLSCA(ARRS,ARRP)
      PARAMETER(NW=40)
      PARAMETER(MNWV2=2*(NW+1)*(NW+1))
      PARAMETER(NLEG=NW+1,NM=NW,NMP=NM+1)
      PARAMETER(NLATG=102,NLONG=128,NLONGP=NLONG+1,IMAXT=3*NLONG/2)
      COMMON/POLY1/PLEG(NLEG,NMP,NLATG),DPLEG(NLEG,NMP,NLATG)
      COMMON/FFTAR1/TRIGS(IMAXT),IFAX(10)
      COMMON/FFTAR2/ARRAY(NLONGP,NLATG),WORK(NLONGP,NLATG)
      DIMENSION ARRS(2,NLEG,NMP),ARRP(NLONG,NLATG)
      IM1=2*NMP+1
      IM2=NLONGP
      DO 200 J=1,NLATG
      DO 120 IM=1,NMP
      DO 120 IC=1,2
      YSUM=0.0
      DO 100 N=1,NLEG
      YSUM=YSUM+ARRS(IC,N,IM)*PLEG(N,IM,J)
  100 CONTINUE
      ARRAY((IM-1)*2+IC,J)=YSUM
  120 CONTINUE
      DO 130 IM=IM1,IM2
      ARRAY(IM,J)=0.0
  130 CONTINUE
  200 CONTINUE
      INC=1
      ISIGN=+1
      JUMP=NLONGP
      LOT=NLATG
      CALL FFT991(ARRAY,WORK,TRIGS,IFAX,INC,JUMP,NLONG,LOT,ISIGN)
      DO 240 J=1,NLATG
      DO 240 I=1,NLONG
      ARRP(I,J)=ARRAY(I,J)
  240 CONTINUE
      RETURN
      END
 


 
 
      SUBROUTINE FTRANS(GRID,WAVE)
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1,NM=NW,NMP=NM+1)
      PARAMETER(NLATG=102 ,NLONG=128 ,NLONGP=NLONG+1,IMAXT=3*NLONG/2)
      COMMON/FFTAR1/TRIGS(IMAXT),IFAX(10)
      COMMON/FFTAR2/ARRAY(NLONGP,NLATG),WORK(NLONGP,NLATG)
      DIMENSION GRID(NLONG,NLATG),WAVE(2,NMP,NLATG)
      DO 60 JG=1,NLATG
      DO 40 IG=1,NLONG
      ARRAY(IG,JG)=GRID(IG,JG)
   40 CONTINUE
      ARRAY(NLONGP,JG)=0.0
   60 CONTINUE
      ISIGN=-1
      INC=1
      JUMP=NLONGP
      LOT=NLATG
      CALL FFT991(ARRAY,WORK,TRIGS,IFAX,INC,JUMP,NLONG,LOT,ISIGN)
      DO 200 JG=1,NLATG
      DO 200 IM=1,NMP
      WAVE(1,IM,JG)=ARRAY(2*IM-1,JG)
      WAVE(2,IM,JG)=ARRAY(2*IM  ,JG)
  200 CONTINUE
      RETURN
      END
 

      SUBROUTINE FILLAR(ARRAYS,VALUE,N)
      DIMENSION ARRAYS(N)
      DO 20 I=1,N
      ARRAYS(I)=VALUE
   20 CONTINUE
      RETURN
      END

      SUBROUTINE STWVFLX
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C    PROGRAM TO compute the Plumb stationary wave activity flux using  C
C    PRESSURE HISTORY FIELDS.                                          C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      PARAMETER(NW=40)
      PARAMETER(NLEG=NW+1)
      PARAMETER(NM=NW)
      PARAMETER(NMP=NW+1)
      PARAMETER(NLONG=128)
      PARAMETER(NLATG=102)
      PARAMETER(NMAND=7,MAND=2)
      COMMON/GAUSS/RADG(NLATG),GWGT(NLATG)
      COMMON/EPSLON/EPS(NLEG,NMP),XXN(NLEG,NMP),XXM(NMP)
      COMMON/CORCOS/CORIOLIS(NLATG),PLEVEL(NMAND)  
      COMMON/STWV/AVGGDU(NLONG,NLATG,MAND),AVGGDV(NLONG,NLATG,MAND),
     1            AVGGDS(NLONG,NLATG,MAND),
     2            XFS(NLONG,NLATG,MAND),YFS(NLONG,NLATG,MAND),
     4            EDGDH(NLONG,NLATG,MAND),EDGDU(NLONG,NLATG,MAND),
     5            EDGDV(NLONG,NLATG,MAND),
     6            ZMH(NLATG,MAND),
     7            ZMU(NLATG,MAND),ZMV(NLATG,MAND)
      DIMENSION EDGDS(NLONG,NLATG,MAND)
      DIMENSION EDSPS(2,NLEG,NMP,MAND),EDSPU(2,NLEG,NMP,MAND)
      DIMENSION EDSPV(2,NLEG,NMP,MAND)
      DIMENSION EDGDUH(NLONG,NLATG,MAND),EDSPUH(2,NLEG,NMP,MAND)
      DIMENSION EDGDVH(NLONG,NLATG,MAND),EDSPVH(2,NLEG,NMP,MAND)
      DIMENSION GRGDUH(NLONG,NLATG,MAND),GRSPUH(2,NLEG,NMP,MAND)
      DIMENSION GRGDVH(NLONG,NLATG,MAND),GRSPVH(2,NLEG,NMP,MAND)
      R=6.371E+06
C.....compute zonal mean fild & global avg T
      DO 100 L=1,MAND
      CALL ZMEAN(AVGGDS(1,1,L),ZMH(1,L))
      CALL ZMEAN(AVGGDU(1,1,L),ZMU(1,L))
      CALL ZMEAN(AVGGDV(1,1,L),ZMV(1,L))
  100 CONTINUE
C.....compute eddy fild  
      DO 120 L=1,MAND
      DO 120 J=1,NLATG
      DO 120 I=1,NLONG
         EDGDH(I,J,L)=AVGGDS(I,J,L)-ZMH(J,L)
C=====compute u' & v' from real u & v
         EDGDU(I,J,L)=AVGGDU(I,J,L)-ZMU(J,L)
         EDGDV(I,J,L)=AVGGDV(I,J,L)-ZMV(J,L)
  120 CONTINUE
C.....compute u'h' and v'h' and T'h'
      DO 240 L=1,MAND
      DO 240 J=1,NLATG
      DO 240 I=1,NLONG
         EDGDUH(I,J,L)=EDGDU(I,J,L)*EDGDH(I,J,L)
         EDGDVH(I,J,L)=EDGDV(I,J,L)*EDGDH(I,J,L)
  240 CONTINUE
      DO 250 L=1,MAND
         CALL TRNSFM(EDGDUH(1,1,L),EDSPUH(1,1,1,L))
         CALL TRNSFM(EDGDVH(1,1,L),EDSPVH(1,1,1,L))
  250 CONTINUE
C.....compute  zonal gradient of u'h', v'h', T'h'
      DO 260 L=1,MAND
      CALL ZNGRSP(EDSPUH(1,1,1,L),GRSPUH(1,1,1,L))
      CALL ZNGRSP(EDSPVH(1,1,1,L),GRSPVH(1,1,1,L))
  260 CONTINUE
CC....transform gradients to gaussian grids
      DO 270 L=1,MAND
         CALL EVLSCA(GRSPUH(1,1,1,L),GRGDUH(1,1,L))
         CALL EVLSCA(GRSPVH(1,1,1,L),GRGDVH(1,1,L))
      DO 270 J=1,NLATG
      DO 270 I=1,NLONG
         GRGDUH(I,J,L)=GRGDUH(I,J,L)/COS(RADG(J))   
         GRGDVH(I,J,L)=GRGDVH(I,J,L)/COS(RADG(J))   
  270 CONTINUE
C.....compute  components of wvflx                       
      DO 280 L=1,MAND
      DO 280 J=1,NLATG
      DO 280 I=1,NLONG
      F1=(PLEVEL(L+4)/PLEVEL(1))*COS(RADG(J))
      F2=2*R*COS(RADG(J))
      XFS(I,J,L)=F1*(EDGDV(I,J,L)**2-GRGDVH(I,J,L)/F2)
      YFS(I,J,L)=F1*(-EDGDU(I,J,L)*EDGDV(I,J,L)+
     1           GRGDUH(I,J,L)/F2)
  280 CONTINUE
      RETURN
      END
 

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C   zonal mean 2-D field                 
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE ZMEAN(FLDIN,FLDOT)
      PARAMETER(NLONG=128,NLATG=102)
      DIMENSION FLDIN(NLONG,NLATG),FLDOT(NLATG)
      XX=FLOAT(NLONG)
      DO 10 J=1,NLATG
         FLDOT(J)=0.
   10 CONTINUE
      DO 100 J=1,NLATG
      DO 100 I=1,NLONG
         FLDOT(J)=FLDOT(J)+FLDIN(I,J)/XX      
  100 CONTINUE
      RETURN
      END
      
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C  1-D zonal gradient in spectral space
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE ZNGRSP(FILDIN,OUTX)
      PARAMETER(NW=40,NLEG=NW+1,NMP=NW+1)
      COMMON/EPSLON/EPS(NLEG,NMP),XXN(NLEG,NMP),XXM(NMP)
      DIMENSION FILDIN(2,NLEG,NMP)                   
      DIMENSION OUTX(2,NLEG,NMP),OUTY(2,NLEG,NMP)
      R=6.371E+06
CC....x component of the gradient
      DO 100 K=1,NMP
      DO 100 J=1,NLEG 
         OUTX(1,J,K)=-XXM(K)*FILDIN(2,J,K)/R
         OUTX(2,J,K)=XXM(K)*FILDIN(1,J,K)/R
  100 CONTINUE
      RETURN
      END

