#!/bin/sh
# seach and replace name

find . -name "*.[gfFsc]*" > zz

while read fname
do 
sed -e "s,1870,1854,g"              $fname > tmp.8
#sed -e "s, FSv2,CFSv2,g"              $fname > tmp.8
#sed -e "s,Prec,T2m,g"              $fname > tmp.8
#sed -e "s,mlo=360,mlo=121,g"              $fname > tmp.8
#sed -e "s,mla=90,mla=56,g"              $fname > tmp.8
#sed -e "s,mla=180,mla=56,g"              $fname > tmp.8

mv tmp.8 $fname
done < zz
\rm zz
