'open /cpc/analysis/verif/ocean/sst/oi/ctl/monoiv2.ctl'
'open /cpc/analysis/verif/ocean/sst/oi/ctl/mask.ctl'
'set gxout fwrite'
'set fwrite sst.oct13-mar14.gr'
'set x 1 360'
'set y 1 180'
'set t 1 12'
'define sstc=ave(sst,t+0,t=350,1yr)'
'modify sstc seasonal'
'set t 384 389'
'd maskout(sst-sstc,mask.2(t=1)-1)'
*'d sst-sstc'
