name: Build ClimateInform Site

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'scripts/**'
      - 'website/**'
      - '.github/workflows/build-site.yml'

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout website repo
        uses: actions/checkout@v4

      - name: Checkout pngs repo
        uses: actions/checkout@v4
        with:
          repository: PeitaoPeng/pngs
          path: pngs

      - name: Set up bash
        run: sudo apt-get update && sudo apt-get install -y bash

      - name: Generate HTML for YEAR
        env:
          YEAR: '2025'
          PNG_ROOT: '${{ github.workspace }}/pngs'
        run: |
          chmod +x generate_month_html.sh generate_year_html.sh
          for M in $(ls pngs/$YEAR); do
            ./generate_month_html.sh "$YEAR" "$M"
          done
          ./generate_year_html.sh "$YEAR"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add website/pages/forecasts
          git commit -m "CI: regenerate site for $YEAR" || echo "No changes to commit."
          git push

