         SUBROUTINE COMINT( NVAR, NPOS, VEC, FRC, INTDAT, KLEV )
C        PROGRAM SMF(INPUT,OUTPUT,UNIT5=INPUT,UNIT6=OUTPUT)
C***********************************************************************
C
C     SMF : MAIN ROUTINE FOR NMC SPECTRAL WEATHER FORECAST MODEL.
C
C***********************************************************************
      save
      include "ptrunk"
      include "pimax"
      include "pjmax"
      include "pkmax"
      include "comcom"
      COMMON/COMCTQ/    CT(KMAX),CQ(KMAX)
      include "comsig"
C-----------------------------------------------------------------------
      COMMON/SCRTCH/QWORK(MNWV3,3),GWORK(IMX,KGMAX)
C-----------------------------------------------------------------------
      include "comctl"
      include "comphc"
      include "commnt"
      include "comtim"
      include "comcon"
      include "comnum"
      include "namcon"
      include "namttl"
C
      COMMON/BSCST/           QZEBAR(MNWV2,KMAX), QDIBAR(MNWV2,KMAX),
     1   QTMBAR(MNWV2,KMAX),  QPSBAR(MNWV2),      QUBAR(MNWV3,KMAX),
     2   QVBAR(MNWV3,KMAX),QPHBAR(MNWV3),QPLBAR(MNWV2)
      COMMON/TSFCA/ TSA(MNWV2)     
      COMMON/COMSCL/ZEVAL,DIVAL,TVAL
C
      PARAMETER( NBIG=5*MNWV2 )
      DIMENSION VEC(NBIG,4),FRC(MNWV2,5)
      dimension LA0im(nend1)
      LOGICAL INTDAT
      data iip/1/
C
c     write(6,*) 'get into COMINT'
      if(iip.eq.1) then
      iip=0
      WRITE(6,NAMCON)
      WRITE(6,111) DELSIG
      WRITE(6,111) CP,HL,GASR,ER,GRAV,STEFAN,SOLCON,TWOMG
      WRITE(6,111) ONE,TWO,THREE,FOUR,FIVE
      WRITE(6,333) KT,KTM,INTSW,INTIR
  111 FORMAT(1H ,12E10.3)
  333 FORMAT(1H ,20I6   )
C
      MEND2=MEND1*2
      JEND2=JEND1+1
      JJMAX=JMAX
      MNKMAX=MNWV2*KMAX
C
CVD$L NOVECTOR
      DO 20 K=1,KMAX
      DEL(K)=DELSIG(K)
   20 CONTINUE
C
      MEND=MEND1-1
      NEND=NEND1-1
      JEND=JEND1-1
      KEND=KMAX
      WRITE(6,100) MEND,NEND,JEND,KEND
  100 FORMAT(1H0,'SMF  MEND=',I2,'  NEND=',I2,'  JEND=',I2,'  KMAX=',I2)
C
C===HORIZONTAL DIFFUSION COEFFICIENTS
C
      FNN1=(NEND1-1)*NEND1
      DK  = HDIFD
      TK  = HDIFT
      DK2 = HDIFD2
      TK2 = HDIFT2
      WRITE(6,111) DK,TK
C
C===LA0,LA1 ARE ARRAYS THAT CONVERT (M,N) INTO DIAGONALWISE NUMBERING
C
      L=0
      DO 1 NN=1,NEND1
      IF(NN.LE.JEND1-MEND1+1) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND1-NN+1
      END IF
CVD$L NOVECTOR
      DO 1 MM=1,MMAX
      L=L+1
      LA0(MM,NN)=L
      if(mm.eq.1) LA0im(nn)=L
    1 CONTINUE
      L=0
      DO 2 NN=1,NEND2
      IF(NN.LE.JEND2-MEND1+1) THEN
      MMAX=MEND1
      ELSE
      MMAX=JEND2-NN+1
      END IF
CVD$L NOVECTOR
      DO 2 MM=1,MMAX
      L=L+1
      LA1(MM,NN)=L
    2 CONTINUE
C
      CALL SETSIG(CI,SI,DEL,SL,CL,RPI,KMAX,KMAXM,KMAXP)
C
      CALL AMHMTM(DEL,RPI,SV,P1,P2,AM,HM,TM,KMAX,KMAXM)
C
      CALL GLATS (JMAXHF, DCOLRAD, DWGT, DWGTCS, DRCS2)
      DO 3 J=1,JMAXHF
      DCOLRA(       J)=    DCOLRAD(J)
C
      COLRAD(       J)=    DCOLRAD(J)
      COLRAD(JMAX+1-J)=PAI-DCOLRAD(J)
      RCS2  (J)=DRCS2 (J)
      WGT(J)=DWGT(J)
      WGTCS(J)=DWGTCS(J)
      PRINT 102,J,COLRAD(J),WGT(J),WGTCS(J)
 102  FORMAT(1H ,I2,2X,F10.7,2X,E13.7,2X,E13.7)
    3 CONTINUE
C
      CALL EPSLON(DEPS,MEND1,NEND2,JEND2,MNWV1)
      DO 4 MN=1,MNWV1
      EPS(MN)=DEPS(MN)
    4 CONTINUE
C
      ISST=0
      CALL GSSTCD(Z00,SATCRI,0)
C
      CALL BMCM (TOV,P1,P2,H1,H2,DEL,CI,BM,CM,DT,SV,AM,KMAX,KMAXP)
C
C  ..... GET BASIC STATE FIELDS
C
      CALL GETBS(NFIN0,QPSBAR,QTMBAR,QDIBAR,QZEBAR,TSA,qwork,LA0,
     1    MNWV0)
C
C  ..... SPECTRAL MANIPULATIONS OF BASIC STATE FIELDS
C
      JEND2 =JEND1+1
C
      CALL DELLNP(QPSBAR,QPHBAR,QPLBAR,EPS,MEND1,NEND1,NEND2,JEND1,
     1            MNWV0,MNWV1,LA0,LA1)
      CALL DZTOUV(QDIBAR,QZEBAR,QUBAR,QVBAR,EPS,MEND1,
     1            NEND1,NEND2,JEND2,MNWV0,
     1            MNWV1,KMAX,LA0,LA1,QWORK(1,1),QWORK(1,2))
C
C  ..... CONSTANTS FOR DIMENSIONALIZATION/NONDIMENSIONALIZTION
C
      ZEVAL = TWOMG
      DIVAL = TWOMG
      DOTVAL= TWOMG
      GEOVAL= TWOMG**2 * ER**2
      TVAL  = TWOMG**2 * ER**2 / GASR
C
      DZEDT =-TWOMG**2
      DDIDT =-TWOMG**2
      DLNPDT= TWOMG
      DTDT  =-TWOMG**3 * ER**2 / GASR
      DDOTDT=-TWOMG
C
      endif
C
C=======================================================================
C=== ENTRY FOR TENDENCY CALCULATIONS ===================================
C=======================================================================
C
C  .... PUT INPUT SPECTRAL VALUES IN CURRENT TIME STEP ARRAYS
C
      CALL RESET(VEC,NBIG*4)
C
C...    CONTRIBUTIONS FROM GEOPOTENTIAL PERTURBATION
C
      IF(NVAR.EQ.4) THEN
      VEC(NPOS+MNWV2 ,2) =  (SNNP1(npos)/(ER*ER))*GEOVAL*SI(KLEV)
     |      /(DDIDT*DEL(Klev))
      IF(KLEV.LT.KMAX) THEN
      VEC(NPOS+MNWV2 ,3) = -(SNNP1(npos)/(ER*ER))*GEOVAL*SI(KLEV+1)
     |      /(DDIDT*DEL(Klev))
      ENDIF
      RETURN
      ENDIF
C
C ..... COMPUTE CONTRIBUTION FROM KLEV-1 (MATRIX A)
C
      IF(KLEV.EQ.1) GO TO 210
C
      CALL RESET(QLNPP,MNWV2)
      CALL RESET(QDIVP,MNWV2*KMAX)
      CALL RESET(QROTP,MNWV2*KMAX)
      CALL RESET(QTMPP,MNWV2*KMAX)
      CALL RESET(QDOTP,MNWV2*KMAX)
C
      IF(NVAR.EQ.1) THEN
       QROTP(NPOS,KLEV-1) = ZEVAL
      ENDIF
      IF(NVAR.EQ.2) THEN
       QDIVP(NPOS,KLEV-1) = DIVAL
      ENDIF
      IF(NVAR.EQ.3) THEN
       QTMPP(NPOS,KLEV-1) = TVAL
      ENDIF
      IF(NVAR.EQ.5) THEN
       QDOTP(NPOS,KLEV-1) = DOTVAL
      END IF
C
      CALL GLOOP
C
      DO 220 I=1,MNWV2
      VEC(I        ,1) = QROTT(I,KLEV)/DZEDT
      VEC(I+MNWV2  ,1) = QDIVT(I,KLEV)/DDIDT
      VEC(I+2*MNWV2,1) = QTMPT(I,KLEV)/DTDT
      VEC(I+4*MNWV2,1) = QDOTT(I,KLEV)/DDOTDT
 220  CONTINUE
C
 210  CONTINUE
C
C ..... COMPUTE CONTRIBUTION FROM KLEV (MATRIX B)
C
      CALL RESET(QLNPP,MNWV2)
      CALL RESET(QDIVP,MNWV2*KMAX)
      CALL RESET(QROTP,MNWV2*KMAX)
      CALL RESET(QTMPP,MNWV2*KMAX)
      CALL RESET(QDOTP,MNWV2*KMAX)
      IF(INTDAT.AND.NVAR.EQ.1.AND.NPOS.EQ.1) CALL RESET(FRC,NBIG)
C
      IF(NVAR.EQ.1) THEN
       QROTP(NPOS,KLEV) = ZEVAL
      ENDIF
      IF(NVAR.EQ.2) THEN
       QDIVP(NPOS,KLEV) = DIVAL
      ENDIF
      IF(NVAR.EQ.3) THEN
       QTMPP(NPOS,KLEV) = TVAL
      ENDIF
C
      IF(NVAR.EQ.5) THEN
      IF(KLEV.LT.KMAX) THEN
       QDOTP(NPOS,KLEV) = DOTVAL
      ELSE IF(KLEV.EQ.KMAX) THEN
       QLNPP(NPOS)      = ONE
      ENDIF
      ENDIF
C
      CALL GLOOP
C
      CALL DEL4(DK,TK,SNNP1,QDER,QDIVT,QDIVP,QTMPT,QTMPP,QROTT,
     1          QROTP,QLNPP,MEND1,NEND1,JEND1,MNWV2,KMAX,
     2          CT,CQ,LA0im)
c     CALL DEL2(DK2,TK2,SNNP1,QDER,QDIVT,QDIVP,QTMPT,QTMPP,QROTT,
c    1          QROTP,QLNPP,MEND1,NEND1,JEND1,MNWV2,KMAX,
c    2          CT,CQ,LA0im)
c
      DO 230 I=1,MNWV2
      VEC(I        ,2) = QROTT(I,KLEV)/DZEDT
      VEC(I+MNWV2  ,2) = QDIVT(I,KLEV)/DDIDT
      VEC(I+2*MNWV2,2) = QTMPT(I,KLEV)/DTDT
      VEC(I+4*MNWV2,2) = QDOTT(I,KLEV)/DDOTDT
 230  CONTINUE
      IF(INTDAT.AND.NVAR.EQ.1.AND.NPOS.EQ.1) then
      CALL SETFRC(FRC,KLEV)
       do 231 i=1,mnwv2
       FRC(i,3)=FRC(i,3)*(-1.)/DTDT
 231   continue
      endif
C
C ..... COMPUTE CONTRIBUTION FROM KLEV+1 (MATRIX C)
C
      IF(KLEV.EQ.KMAX) GO TO 240
C
      CALL RESET(QLNPP,MNWV2)
      CALL RESET(QDIVP,MNWV2*KMAX)
      CALL RESET(QROTP,MNWV2*KMAX)
      CALL RESET(QTMPP,MNWV2*KMAX)
      CALL RESET(QDOTP,MNWV2*KMAX)
C
      IF(NVAR.EQ.1) THEN
       QROTP(NPOS,KLEV+1) = ZEVAL
      ENDIF
      IF(NVAR.EQ.2) THEN
       QDIVP(NPOS,KLEV+1) = DIVAL
      ENDIF
      IF(NVAR.EQ.3) THEN
       QTMPP(NPOS,KLEV+1) = TVAL
      ENDIF
C
      IF(NVAR.EQ.5) THEN
      IF(KLEV.LT.KMAX-1) THEN
       QDOTP(NPOS,KLEV+1) = DOTVAL
      ELSE IF (KLEV.EQ.KMAX-1) THEN
       QLNPP(NPOS)        = ONE
      END IF
      END IF
C
      CALL GLOOP
C
      DO 250 I=1,MNWV2
      VEC(I        ,3) = QROTT(I,KLEV)/DZEDT
      VEC(I+MNWV2  ,3) = QDIVT(I,KLEV)/DDIDT
      VEC(I+2*MNWV2,3) = QTMPT(I,KLEV)/DTDT
      VEC(I+4*MNWV2,3) = QDOTT(I,KLEV)/DDOTDT
 250  CONTINUE
C
 240  CONTINUE
C
C ..... COMPUTE CONTRIBUTION FROM KMAX (MATRIX D)
C
      IF(KLEV.LE.KMAX-2) THEN
      IF(NVAR.EQ.5) THEN
C
      CALL RESET(QLNPP,MNWV2)
      CALL RESET(QDIVP,MNWV2*KMAX)
      CALL RESET(QROTP,MNWV2*KMAX)
      CALL RESET(QTMPP,MNWV2*KMAX)
      CALL RESET(QDOTP,MNWV2*KMAX)
C
       QLNPP(NPOS)  =  ONE
C
      CALL GLOOP
C
      DO 270 I=1,MNWV2
      VEC(I        ,4) = QROTT(I,KLEV)/DZEDT
      VEC(I+MNWV2  ,4) = QDIVT(I,KLEV)/DDIDT
      VEC(I+2*MNWV2,4) = QTMPT(I,KLEV)/DTDT
      VEC(I+4*MNWV2,4) = QDOTT(I,KLEV)/DDOTDT
 270  CONTINUE
C
      ENDIF
      ENDIF
C
      RETURN
      END
