      SUBROUTINE SLNOUT(SOLN,FRCOUT)
      save
      include "ptrunk"
      include "pimax"
      include "pjmax"
      include "pkmax"
      include "comnum"
      include "comphc"
      PARAMETER(MNWV2=JEND1*(JEND1+1)-(JEND1-NEND1)*(JEND1-NEND1+1)
     3               -(JEND1-MEND1)*(JEND1-MEND1+1),
     4          MNWV3=MNWV2+2*MEND1, NEND2=NEND1+1, IMAXT=IMAX*3/2 )
      DIMENSION SOLN(MNWV2,5,KMAX),FRCOUT(MNWV2,5,KMAX)
      DIMENSION QOUT(MNWV2,KMAX),QWORK(MNWV2,2),IDATE(4)
      COMMON/BSCST/           QZEBAR(MNWV2,KMAX), QDIBAR(MNWV2,KMAX),
     1   QTMBAR(MNWV2,KMAX),  QPSBAR(MNWV2),      QUBAR(MNWV3,KMAX),
     2   QVBAR(MNWV3,KMAX),QPHBAR(MNWV3),QPLBAR(MNWV2)
      COMMON/COMSCL/ZEVAL,DIVAL,TVAL
      COMMON/FRCSCL/scales(5)
      COMMON/COMBIT/TRIGS(IMAXT),SNNP1(MNWV2),IFAX(10),LAB(4),
     1              LA0(MEND1,NEND1),LA1(MEND1,NEND2)
      COMMON/TSFCA/TSA(MNWV2)
      DIMENSION QPSANM(MNWV2),QDIANM(MNWV2,KMAX),
     1          QZEANM(MNWV2,KMAX),QTMANM(MNWV2,KMAX),qq(MNWV2)
      data iudiag/66/
C
C  WRITE LABEL
      THOUR = 0.
      IDATE(1) = 0
      IDATE(2) = 1
      IDATE(3) = 1
      IDATE(4) = 92
      WRITE(IUDIAG) THOUR,IDATE
C
C WRITE TOTAL FIELDS
      IHDIM=MNWV2
C
C===  LN SURFACE PRESSURE  ===
C
      DO 10 I=1,MNWV2
      QOUT(I,1) = SOLN(I,5,KMAX) + QPSBAR(I)
  10  CONTINUE
C
      NLEV=1
      CONFAC=ONE
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  DIVERGENCE ===
C
      DO 20 K=1,KMAX
      DO 20 I=1,MNWV2
      QOUT(I,K) =  QDIBAR(I,K) + DIVAL*SOLN(I,2,K)
  20  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  VORTICITY  ===
C
      DO 30 K=1,KMAX
      DO 30 I=1,MNWV2
      QOUT(I,K) =  QZEBAR(I,K) + ZEVAL*SOLN(I,1,K)
  30  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  SPECIFIC HUMIDITY  ===
C
      CONFAC = ZERO
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  VIRTUAL TEMPERATURE  ===
C
      DO 40 K=1,KMAX
      DO 40 I=1,MNWV2
      QOUT(I,K) = QTMBAR(I,K) + TVAL*SOLN(I,3,K)
  40  CONTINUE
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C=====write out tsfc
C
      NLEV=1
      CONFAC=ONE
      CALL SCLOUT(IUDIAG,TSA,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C=====write out forcings
C
      dzdt = twomg**2
      ddidt = twomg**2
      dsigdt= twomg
      dtdt = twomg**3 * er**2 / gasr
      zscl = twomg**2 * er**2 / grav
      scales(1) = dzdt
      scales(2) = ddidt
      scales(3) = dtdt
      scales(4) = zscl
      scales(5) = dsigdt
C
C===  VORTICITY forcing ===
C
      DO 25 K=1,KMAX
      DO 25 I=1,MNWV2
      QOUT(I,K) =  scales(1)*FRCOUT(I,1,K)
  25  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  DIVERGENCE forcing ===
C
      DO 35 K=1,KMAX
      DO 35 I=1,MNWV2
      QOUT(I,K) =   scales(2)*FRCOUT(I,2,K)
  35  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  TEMPERATURE forcing ===
C
      DO 45 K=1,KMAX
      DO 45 I=1,MNWV2
      QOUT(I,K) =   scales(3)*FRCOUT(I,3,K)
  45  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C     write(6,*)'ft=    '
C     write(6,222) QOUT
222   format(8E10.2)
C
C===  GEOPOTENTIAL forcing ===
C
      DO 55 K=1,KMAX
      DO 55 I=1,MNWV2
      QOUT(I,K) =   scales(4)*FRCOUT(I,4,K)
  55  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  CONTINUITY forcing ===
C
      DO 60 K=1,KMAX
      DO 60 I=1,MNWV2
      QOUT(I,K) =   scales(5)*FRCOUT(I,5,K)
  60  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C WRITE BASIC STATE FIELDS
      IDATE(1)=1
      WRITE(IUDIAG) THOUR,IDATE
      IHDIM=MNWV2
C
C===  LN SURFACE PRESSURE  ===
C
      DO 11 I=1,MNWV2
      QOUT(I,1) = QPSBAR(I)
  11  CONTINUE
C
      NLEV=1
      CONFAC=ONE
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  DIVERGENCE ===
C
      DO 21 K=1,KMAX
      DO 21 I=1,MNWV2
      QOUT(I,K) = QDIBAR(I,K)
  21  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  VORTICITY  ===
C
      DO 31 K=1,KMAX
      DO 31 I=1,MNWV2
      QOUT(I,K) = QZEBAR(I,K)
  31  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  SPECIFIC HUMIDITY  ===
C
      CONFAC = ZERO
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  VIRTUAL TEMPERATURE  ===
C
      DO 41 K=1,KMAX
      DO 41 I=1,MNWV2
      QOUT(I,K) = QTMBAR(I,K)
  41  CONTINUE
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C=====write out tsfc
C
      NLEV=1
      CONFAC=ONE
      CALL SCLOUT(IUDIAG,TSA,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C=====write out forcings
C
C===  VORTICITY forcing ===
C
      DO 26 K=1,KMAX
      DO 26 I=1,MNWV2
      QOUT(I,K) =  scales(1)*FRCOUT(I,1,K)
  26  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  DIVERGENCE forcing ===
C
      DO 36 K=1,KMAX
      DO 36 I=1,MNWV2
      QOUT(I,K) =   scales(2)*FRCOUT(I,2,K)
  36  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  TEMPERATURE forcing ===
C
      DO 46 K=1,KMAX
      DO 46 I=1,MNWV2
      QOUT(I,K) =   scales(3)*FRCOUT(I,3,K)
  46  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  GEOPOTENTIAL forcing ===
C
      DO 56 K=1,KMAX
      DO 56 I=1,MNWV2
      QOUT(I,K) =   scales(4)*FRCOUT(I,4,K)
  56  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  CONTINUITY forcing ===
C
      DO 61 K=1,KMAX
      DO 61 I=1,MNWV2
      QOUT(I,K) =   scales(5)*FRCOUT(I,5,K)
  61  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C WRITE GCM ANOM plus BASIC STATE
      IDATE(1)=2
      WRITE(IUDIAG) THOUR,IDATE
      MNWV0=MNWV2/2
C===  read in gcm anomlies
      NM=28
      CALL GETANOM(NM,QPSANM,QTMANM,QDIANM,QZEANM,qq,LA0,
     1   MNWV0,KMAX,MEND1,NEND1,JEND1)
C
C===  LN SURFACE PRESSURE  ===
C
      DO 12 I=1,MNWV2
      QOUT(I,1) = QPSANM(I)+QPSBAR(I)
  12  CONTINUE
C
      NLEV=1
      CONFAC=ONE
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  DIVERGENCE ===
C
      DO 22 K=1,KMAX
      DO 22 I=1,MNWV2
      QOUT(I,K) = QDIANM(I,K)+QDIBAR(I,K)
  22  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  VORTICITY  ===
C
      DO 32 K=1,KMAX
      DO 32 I=1,MNWV2
      QOUT(I,K) = QZEANM(I,K)+QZEBAR(I,K)
  32  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  SPECIFIC HUMIDITY  ===
C
      CONFAC = ZERO
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  VIRTUAL TEMPERATURE  ===
C
      DO 42 K=1,KMAX
      DO 42 I=1,MNWV2
      QOUT(I,K) = QTMANM(I,K)+QTMBAR(I,K)
  42  CONTINUE
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C=====write out tsfc
C
      NLEV=1
      CONFAC=ONE
      CALL SCLOUT(IUDIAG,TSA,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C=====write out forcings
C
C===  VORTICITY forcing ===
C
      DO 27 K=1,KMAX
      DO 27 I=1,MNWV2
      QOUT(I,K) =  scales(1)*FRCOUT(I,1,K)
  27  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  DIVERGENCE forcing ===
C
      DO 37 K=1,KMAX
      DO 37 I=1,MNWV2
      QOUT(I,K) =   scales(2)*FRCOUT(I,2,K)
  37  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  TEMPERATURE forcing ===
C
      DO 47 K=1,KMAX
      DO 47 I=1,MNWV2
      QOUT(I,K) =   scales(3)*FRCOUT(I,3,K)
  47  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  GEOPOTENTIAL forcing ===
C
      DO 57 K=1,KMAX
      DO 57 I=1,MNWV2
      QOUT(I,K) =   scales(4)*FRCOUT(I,4,K)
  57  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
C===  CONTINUITY forcing ===
C
      DO 62 K=1,KMAX
      DO 62 I=1,MNWV2
      QOUT(I,K) =   scales(5)*FRCOUT(I,5,K)
  62  CONTINUE
C
      CONFAC = ONE
      NLEV = KMAX
      CALL SCLOUT(IUDIAG,QOUT,IHDIM,NLEV,CONFAC,QWORK,'SPEC',
     *   MEND1,NEND1,JEND1,LA0)
C
      WRITE(6,5000)IDATE,THOUR
 5000 FORMAT(' DONE WITH WRPROG AT ',4I5,2X,F9.1)
C
      RETURN
      END
