      SUBROUTINE GETABG(NSAV,A,B,G,N,KLEV)
      DIMENSION A(N,N),B(N),G(N,N)
      BACKSPACE NSAV
      BACKSPACE NSAV
      READ(NSAV) LEV
      IF(LEV.EQ.KLEV) THEN
         READ(NSAV) A,B,G
        ELSE IF(LEV.EQ.KLEV+1) THEN
         BACKSPACE NSAV
         BACKSPACE NSAV
         READ(NSAV) A,B,G
        ELSE
         WRITE(6,*) ' UNEXPECTED ORDER OF TEMPORARY DATA FOR GETABG'
         STOP
      ENDIF
      RETURN
      END
