      SUBROUTINE SCLOUT
     1 (IUDIAG,FIELD,NHARM,LEVS,FACT1,FLDOUT,IVAR,
     2 MEND1,NEND1,JEND1,LA0)
C
      DIMENSION FIELD(NHARM,LEVS)
      DIMENSION FLDOUT(NHARM,2)
      DIMENSION LA0(MEND1,NEND1)
      CHARACTER*4 IVAR
C
      DO 1 K=1,LEVS
      DO 2 I=1,NHARM
      FLDOUT(I,1) = FACT1 * FIELD(I,K)
  2   CONTINUE
C
      IF(IVAR.EQ.'SPEC') THEN
      CALL TRANSP(FLDOUT(1,1),NHARM,MEND1,NEND1,JEND1,1,LA0,
     *            FLDOUT(1,2),1)
      END IF
      ixwave=mend1
      iywave=nend1
      CALL WRFLD (FLDOUT(1,1),NHARM,1,IUDIAG,ixwave,iywave)
C
  1   CONTINUE
C
      RETURN
      END
